--- # Install Scalr

- name: Install Scalr
  apt:
    name: scalr-server
    state: present
  become: yes
  notify:
    - scalr wizard

- name: Set password
  shell: "/tmp/set_password.py {{ admin_password }}"
  notify:
    - reconfigure
