--- # Install Scalr repo for Debian systems

- name: Install Scalr repo
  shell: "curl -L {{ deb_source_repo }}| sudo bash"

- name: Install Scalr
  apt:
    name: scalr-server
    state: latest
  notify: scalr-server-wizard

- meta: flush_handlers
