--- # Install Scalr repo for Debian systems

- name: Install Open Source Scalr repo
  shell: >
    curl -L https://packagecloud.io/install/repositories/scalr/scalr-server-oss/script.deb
    | sudo bash

- name: Install Scalr
  apt:
    name: scalr-server
    state: latest
  notify: scalr-server-wizard

- meta: flush_handlers
