--- # Install Scalr repo for Debian systems

- name: Install Open Source Scalr repo
  apt:
    deb: https://packagecloud.io/install/repositories/scalr/scalr-server-oss/script.deb

- name: Install Scalr
  apt:
    name: scalr-server
    state: present
    update_cache: yes
  become: yes
  notify:
    - scalr wizard
